import React, { FormEvent, useState } from "react";
import AppLayout from "../components/layout/AppLayout";
import { postChat } from "../services/chatApi";
import { ChatRequest, ChatResponse, MemoryItem } from "../types/api";
import MemoryPanel from "../components/ai/MemoryPanel";
import AgentStatus from "../components/status/AgentStatus";
import PipelineStatus, { PipelineStep } from "../components/ai/PipelineStatus";
import { useHealth } from "../hooks/useHealth";
import { useMemoryOperation } from "../hooks/useMemoryOperation";

const EMPTY_MEMORIES: MemoryItem[] = [];

export default function AIWorkspace() {
  const [messages, setMessages] = useState<{ role: 'user' | 'assistant'; text: string }[]>([]);
  const [input, setInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [lastResponse, setLastResponse] = useState<ChatResponse | null>(null);
  const retentionStatus = useMemoryOperation(lastResponse);
  const statusResponse = lastResponse ? {
    ...lastResponse,
    memory_stored: retentionStatus === "stored",
    memory_storage_status: retentionStatus,
  } : null;
  const { health, loading: healthLoading, error: healthError, refresh } = useHealth(60000);
  const [pipeline, setPipeline] = useState<PipelineStep[]>([
    { label: 'User request', detail: 'Send a message to the existing chat API', state: 'pending' },
    { label: 'Memory recall', detail: 'Find relevant Hindsight context', state: 'pending' },
    { label: 'AI generation', detail: 'Use recalled facts as context', state: 'pending' },
    { label: 'Memory storage', detail: 'Retain the new interaction', state: 'pending' },
  ]);

  async function send(event?: FormEvent) {
    event?.preventDefault();
    if (!input.trim()) return;
    setLoading(true);
    setError(null);
    setLastResponse(null);
    setPipeline([
      { label: 'User request', detail: 'Request sent to the configured backend', state: 'complete' },
      { label: 'Memory recall', detail: 'Searching relevant Hindsight context', state: 'active' },
      { label: 'AI generation', detail: 'Waiting for the AI response', state: 'pending' },
      { label: 'Memory storage', detail: 'Will store after generation', state: 'pending' },
    ]);

    const userMsg = input.trim();
    setMessages((current) => [...current, { role: 'user', text: userMsg }]);
    setInput("");
    const req: ChatRequest = { user_id: 'user_dev', message: userMsg };
    try {
      const response = await postChat(req);
      setMessages((current) => [...current, { role: 'assistant', text: response.response }]);
      setLastResponse(response);
      setPipeline([
        { label: 'User request', detail: 'Received by the existing chat API', state: 'complete' },
        {
          label: 'Memory recall',
          detail: response.memory_recall_success ? `Success — ${response.memories_recalled_count} relevant memories` : 'Failed; AI continued without memory',
          state: response.memory_recall_success ? 'complete' : 'failed',
        },
        { label: 'AI generation', detail: response.ai_generation_success ? `Generated by ${response.llm_provider} · ${response.llm_model}` : 'Generation was not confirmed', state: response.ai_generation_success ? 'complete' : 'failed' },
        { label: 'Memory storage', detail: response.memory_storage_status === 'pending' ? 'Accepted by Hindsight; extraction pending' : response.memory_stored ? 'Stored successfully' : 'Storage failed', state: response.memory_storage_status === 'pending' ? 'active' : response.memory_stored ? 'complete' : 'failed' },
      ]);
    } catch (reason: any) {
      setError(reason?.message ?? 'Unknown error');
      setPipeline((current) => current.map((step, index) => index === 0 ? { ...step, state: 'failed' } : step));
    } finally {
      setLoading(false);
    }
  }

  return (
    <AppLayout>
      <div className="page-wrap">
        <div className="page-heading">
          <div><p className="eyebrow">ASK RECALLMEET</p><h1>AI agent</h1><p>Ask about past conversations, meeting context, or what to bring into the room.</p></div>
        </div>
        <div className="chat-layout">
          <section className="surface chat-panel" aria-label="AI chat">
            <div className="chat-messages" aria-live="polite">
              {messages.length === 0 && <div className="chat-welcome"><span className="welcome-mark" aria-hidden="true">R</span><h2>What should we remember?</h2><p>Ask a question or share meeting context. The agent recalls relevant Hindsight memories before answering.</p></div>}
              {messages.map((message, index) => <div className={`chat-bubble chat-bubble-${message.role}`} key={`${message.role}-${index}`}>{message.text}</div>)}
              {loading && <div className="ai-processing"><span className="processing-bars" aria-hidden="true"><i /><i /><i /></span>Recalling context and preparing a response…</div>}
              {error && <p className="error-state" role="alert">{error}</p>}
            </div>
            <form className="chat-compose" onSubmit={send}>
              <textarea aria-label="Message the AI agent" placeholder="Ask about a previous meeting or share new context…" rows={2} value={input} onChange={(event) => setInput(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); void send(); } }} />
              <button className="button button-accent" type="submit" aria-label="Send message" disabled={loading || !input.trim()}>{loading ? '…' : 'Send'}<span aria-hidden="true">↗</span></button>
            </form>
          </section>
          <aside className="chat-side">
            <PipelineStatus steps={pipeline.map((step) => step.label === 'Memory storage' && statusResponse
              ? { ...step, detail: retentionStatus === 'pending' ? 'Accepted by Hindsight; extraction pending' : retentionStatus === 'stored' ? 'Stored successfully' : 'Storage failed', state: retentionStatus === 'pending' ? 'active' : retentionStatus === 'stored' ? 'complete' : 'failed' }
              : step)} label="Memory pipeline" />
            <AgentStatus health={health} loading={healthLoading} error={Boolean(healthError)} lastResponse={statusResponse} onRefresh={() => void refresh()} compact />
            <section className="surface chat-memory">
              <div className="section-heading"><div><p className="eyebrow">MEMORY TRACE</p><h2>Recalled context</h2></div></div>
              <MemoryPanel userId="user_dev" memories={lastResponse?.memories_recalled ?? EMPTY_MEMORIES} recallSucceeded={lastResponse?.memory_recall_success} />
            </section>
          </aside>
        </div>
      </div>
    </AppLayout>
  );
}
