import React from "react";
import { ChatResponse } from "../../types/api";

function renderLine(line: string, index: number) {
  const trimmed = line.trim();
  if (!trimmed) return <div className="briefing-spacer" key={`space-${index}`} />;
  const heading = trimmed.match(/^(?:#{1,3}\s+|\d+[.)]\s+)(.+)$/);
  if (heading) return <h3 key={index}>{heading[1].replace(/\*\*/g, "")}</h3>;
  const bullet = trimmed.match(/^(?:[-*•]\s+)(.+)$/);
  const content = bullet ? bullet[1] : trimmed;
  const fragments = content.split(/(\*\*[^*]+\*\*)/g).map((part, partIndex) =>
    part.startsWith("**") && part.endsWith("**")
      ? <strong key={partIndex}>{part.slice(2, -2)}</strong>
      : part,
  );
  return bullet
    ? <p className="briefing-bullet" key={index}><span aria-hidden="true">·</span>{fragments}</p>
    : <p key={index}>{fragments}</p>;
}

export default function PreparationBrief({ result }: { result: ChatResponse }) {
  return (
    <section className="surface briefing" aria-live="polite">
      <div className="section-heading">
        <div><p className="eyebrow">PERSONALIZED PREPARATION</p><h2>Meeting briefing</h2></div>
        <span className="quiet-tag">Generated by {result.llm_provider} · {result.llm_model}</span>
      </div>
      <div className="briefing-body">{result.response.split("\n").map(renderLine)}</div>
      <div className="briefing-footnote">{result.memory_recall_success ? `${result.memories_recalled_count} relevant memories were included in this request.` : "Memory recall was unavailable; the agent answered from the meeting details provided."}</div>
    </section>
  );
}